apiVersion: apps/v1
kind: Deployment
metadata:
  name: kv-store-deployment
  labels:
    app: kv-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kv-store
  template:
    metadata:
      labels:
        app: kv-store
    spec:
      containers:
        - name: kv-store
          image: pankajmirdha/kv-store:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
          imagePullPolicy: Always
