---
apiVersion: v1
kind: Service
metadata:
  name: kv-store-service
spec:
  selector:
    app: kv-store
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer  # Change to NodePort if you're on Minikube
